name: SolidHealthDiary
description: 'Secure POD storage of a health diary.'
publish_to: 'none'
version: 0.0.1+0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  solidpod:
    path: solidpod # Use a local path whilst solidpod is under development.
    ## git:
    ##   url: https://github.com/anusii/solidpod
    ##   ref: main
  universal_io: ^2.2.2
  window_manager: ^0.3.7
  
flutter_launcher_icons:
  image_path: "assets/images/keypod_logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/images/keypod_logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/keypod_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/keypod_logo.png"

dev_dependencies:
  build_runner: ^2.4.7
  dart_code_metrics:
    git:
      url: https://github.com/anusii/dart-code-metrics.git
      ref: main
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  ubuntu_lints: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/keypod_image.jpg
    - assets/images/keypod_logo.png
